export const GET_POLICY = 'GET_POLICY';
export const GET_POLICY_PENDING = 'GET_POLICY_PENDING';
export const GET_POLICY_FULFILLED = 'GET_POLICY_FULFILLED';
export const GET_POLICY_REJECTED = 'GET_POLICY_REJECTED';

export const GET_COMPANIES = 'GET_COMPANIES';
export const GET_COMPANIES_PENDING = 'GET_COMPANIES_PENDING';
export const GET_COMPANIES_FULFILLED = 'GET_COMPANIES_FULFILLED';
export const GET_COMPANIES_REJECTED = 'GET_COMPANIES_REJECTED';

export const GET_SERVICES = 'GET_SERVICES';
export const GET_SERVICES_PENDING = 'GET_SERVICES_PENDING';
export const GET_SERVICES_FULFILLED = 'GET_SERVICES_FULFILLED';
export const GET_SERVICES_REJECTED = 'GET_SERVICES_REJECTED';

export const GET_CHECKED_SERVICES = 'GET_CHECKED_SERVICES';
export const GET_CHECKED_SERVICES_PENDING = 'GET_SERVICES_CHECKED_PENDING';
export const GET_CHECKED_SERVICES_FULFILLED = 'GET_SERVICES_CHECKED_FULFILLED';
export const GET_CHECKED_SERVICES_REJECTED = 'GET_SERVICES_CHECKED_REJECTED';

export const DEL_DATA = 'DEL_DATA';